server:
  servlet:
    context-path: /hr

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staff_recruitment_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: Qw123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false

project:
  directory: /home/ubuntu/hr_assist_bot/
  cv_directory: candidates/cv
  assignment_directory: assignments
  assignment_result_directory: candidates/assignment_results
